---
title: "Linear Models"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Load NYC Airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
  
```


```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) + 
  geom_point()
```


Let's fit a linear model.....

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```


Let's look at this.....

```{r}
summary(fit)
summary(fit)$coef

fit %>% broom::tidy()
```


If you want to present output....

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Borough:")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```


## Diagnostics

```{r}
modelr::add_residuals(data = nyc_airbnb, model = fit) %>% 
  ggplot(aes(x = resid)) + 
  geom_density() + 
  xlim(-200, 200)
```

## Interactions? Nesting?

Let's try a different model ... 

```{r}
fit = lm(price ~ stars + room_type, data = nyc_airbnb)

broom::tidy(fit)


fit2 = lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)

broom::tidy(fit2)
```


Let's try nesting ... 

```{r}
nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(borough, lm_results) %>% 
  unnest(lm_results) %>% 
  filter(term == "stars")
```

Look at neighboorhoods in Manhattan....

```{r}
## effect of room_type on stars 
manhattan_lm_results_df =
  nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(-borough) %>% 
  relocate(neighbourhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(neighbourhood, lm_results) %>% 
  unnest(lm_results) ## unnest multiple columns but they have to be in same size. 


manhattan_lm_results_df %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) +
  geom_density()
## graph showing that stars does not really have an effect regarding the type of rooms


manhattan_lm_results_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) + 
  geom_point() + 
  facet_grid(~term) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```








